package com.altinntech.clicksave.core.utils.migration;

import com.altinntech.clicksave.log.CSLogger;
import lombok.Setter;

import java.io.BufferedWriter;
import java.io.File;
import java.io.FileWriter;
import java.io.IOException;
import java.time.LocalDateTime;

public class MigrationWriter {

    @Setter
    private static String directoryPath = "";
    private static String migrationText = "";

    public static void writeToMigration(String sql) {
        migrationText += "\n" + sql;
    }

    public static void createMigration(String tableName) {
        if (migrationText.isEmpty() || directoryPath.isEmpty()) return;
        String fileName = getTimestamp() + "_" + tableName + "_" + "clicksave-migration.sql";
        String filePath = directoryPath;
        try {
            File file = new File(filePath, fileName);
            if (!file.exists()) {
                file.createNewFile();
            }

            FileWriter fw = new FileWriter(file.getAbsoluteFile());
            BufferedWriter bw = new BufferedWriter(fw);
            bw.write("-- Auto-generated by clicksave\n\n" + migrationText);
            bw.close();

            CSLogger.info("Created migration file: " + file.getPath());
        } catch (IOException e) {
            e.printStackTrace();
        } finally {
            migrationText = "";
        }
    }

    private static String getTimestamp() {
        LocalDateTime date = LocalDateTime.now();
        return String.valueOf(date.getYear()) +
                String.valueOf(date.getMonthValue()) +
                String.valueOf(date.getDayOfMonth()) +
                "_" +
                String.valueOf(date.getNano());
    }
}
